[project]
name = "llms-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pytest>=8.3.4",
    "torch>=2.5.1",
    "torchvision>=0.20.1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]